# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Plugin Execution and Upload

on:
 push:
    branches:
      - main


jobs:
  build-and-upload:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run Maven Plugin
      run: mvn site

    - name: Upload Maven Site Output
      uses: actions/upload-artifact@v4
      with:
        name: maven-site
        path: target/site

